service:
  name: oltrix

custom:
  s3Sync:
    - bucketName: ${self:provider.stage}-oltrix-frontend
      localDir: dist/
      bucketPrefix: oltrix-frontend/  

plugins:
  - serverless-plugin-typescript
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  profile: serverless
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          method: get
          path: /

resources:
  Resources:
    ClientBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-oltrix-frontend
  Outputs:
    ClientBucketKey:
      Value: !Ref ClientBucket          